name: utc_time_zone_converter
description: A convenient tool for converting time with a time zone in UTC+ format.
version: 1.0.1
repository: https://github.com/cyrax111/utc_time_zone_converter

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
