name: utc_time_zone_converter
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/cyrax111/utc_time_zone_converter

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
